spring:
  application:
    name: springboot-developer
  jpa:
    #전송쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    
  h2:
    console:
      enabled: true
    
    #테이블 생성 후 data.sql 실행
    defer-datasource-initialization: true
        
